//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace UrunDogrulama.UreticiUrunDogrulama {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UreticiDogrulamaReceiverBinding", Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Dogrulama/Uretici")]
    public partial class UreticiDogrulamaReceiverService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UreticiDogrulamaBildirOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UreticiDogrulamaReceiverService() {
            this.Url = global::UrunDogrulama.Properties.Settings.Default.UrunDogrulama_UreticiUrunDogrulama_UreticiDogrulamaReceiverService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UreticiDogrulamaBildirCompletedEventHandler UreticiDogrulamaBildirCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://its.iegm.gov.tr/bildirim/BR/v1/Dogrulama/UreticiDogrulamaBildirimRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UreticiDogrulamaBildirimCevap", Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Dogrulama/Uretici")]
        public UreticiDogrulamaBildirimCevapType UreticiDogrulamaBildir([System.Xml.Serialization.XmlElementAttribute(Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Dogrulama/Uretici")] UreticiDogrulamaBildirimType UreticiDogrulamaBildirim) {
            object[] results = this.Invoke("UreticiDogrulamaBildir", new object[] {
                        UreticiDogrulamaBildirim});
            return ((UreticiDogrulamaBildirimCevapType)(results[0]));
        }
        
        /// <remarks/>
        public void UreticiDogrulamaBildirAsync(UreticiDogrulamaBildirimType UreticiDogrulamaBildirim) {
            this.UreticiDogrulamaBildirAsync(UreticiDogrulamaBildirim, null);
        }
        
        /// <remarks/>
        public void UreticiDogrulamaBildirAsync(UreticiDogrulamaBildirimType UreticiDogrulamaBildirim, object userState) {
            if ((this.UreticiDogrulamaBildirOperationCompleted == null)) {
                this.UreticiDogrulamaBildirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUreticiDogrulamaBildirOperationCompleted);
            }
            this.InvokeAsync("UreticiDogrulamaBildir", new object[] {
                        UreticiDogrulamaBildirim}, this.UreticiDogrulamaBildirOperationCompleted, userState);
        }
        
        private void OnUreticiDogrulamaBildirOperationCompleted(object arg) {
            if ((this.UreticiDogrulamaBildirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UreticiDogrulamaBildirCompleted(this, new UreticiDogrulamaBildirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Dogrulama/Uretici")]
    public partial class UreticiDogrulamaBildirimType {
        
        private string dtField;
        
        private string frField;
        
        private UreticiDogrulamaBildirimTypeURUN[] uRUNLERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DT {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FR {
            get {
                return this.frField;
            }
            set {
                this.frField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("URUN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UreticiDogrulamaBildirimTypeURUN[] URUNLER {
            get {
                return this.uRUNLERField;
            }
            set {
                this.uRUNLERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Dogrulama/Uretici")]
    public partial class UreticiDogrulamaBildirimTypeURUN {
        
        private string gTINField;
        
        private string bnField;
        
        private string snField;
        
        private System.DateTime xdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GTIN {
            get {
                return this.gTINField;
            }
            set {
                this.gTINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BN {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SN {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime XD {
            get {
                return this.xdField;
            }
            set {
                this.xdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Dogrulama/Uretici")]
    public partial class UreticiDogrulamaBildirimCevapType {
        
        private string bILDIRIMIDField;
        
        private UreticiDogrulamaBildirimCevapTypeURUNDURUM[] uRUNLERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILDIRIMID {
            get {
                return this.bILDIRIMIDField;
            }
            set {
                this.bILDIRIMIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("URUNDURUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UreticiDogrulamaBildirimCevapTypeURUNDURUM[] URUNLER {
            get {
                return this.uRUNLERField;
            }
            set {
                this.uRUNLERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Dogrulama/Uretici")]
    public partial class UreticiDogrulamaBildirimCevapTypeURUNDURUM {
        
        private string gTINField;
        
        private string snField;
        
        private string ucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GTIN {
            get {
                return this.gTINField;
            }
            set {
                this.gTINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SN {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UC {
            get {
                return this.ucField;
            }
            set {
                this.ucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void UreticiDogrulamaBildirCompletedEventHandler(object sender, UreticiDogrulamaBildirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UreticiDogrulamaBildirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UreticiDogrulamaBildirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UreticiDogrulamaBildirimCevapType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UreticiDogrulamaBildirimCevapType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591