//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Kaynak kodu Microsoft.VSDesigner tarafından otomatik üretilmiş , Sürüm 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DeclarationServices.VerificationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UrunDogrulamaReceiverBinding", Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/UrunDogrulama/Genel")]
    public partial class UrunDogrulamaReceiverService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UrunDogrulamaBildirOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UrunDogrulamaReceiverService() {
            this.Url = global::DeclarationServices.Properties.Settings.Default.DeclarationServices_VerificationService_UrunDogrulamaReceiverService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UrunDogrulamaBildirCompletedEventHandler UrunDogrulamaBildirCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://its.iegm.gov.tr/bildirim/BR/v1/UrunDogrulama/UrunDogrulamaBildirimRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UrunDogrulamaBildirimCevap", Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/UrunDogrulama/Genel")]
        public UrunDogrulamaBildirimCevapType UrunDogrulamaBildir([System.Xml.Serialization.XmlElementAttribute(Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/UrunDogrulama/Genel")] UrunDogrulamaBildirimType UrunDogrulamaBildirim) {
            object[] results = this.Invoke("UrunDogrulamaBildir", new object[] {
                        UrunDogrulamaBildirim});
            return ((UrunDogrulamaBildirimCevapType)(results[0]));
        }
        
        /// <remarks/>
        public void UrunDogrulamaBildirAsync(UrunDogrulamaBildirimType UrunDogrulamaBildirim) {
            this.UrunDogrulamaBildirAsync(UrunDogrulamaBildirim, null);
        }
        
        /// <remarks/>
        public void UrunDogrulamaBildirAsync(UrunDogrulamaBildirimType UrunDogrulamaBildirim, object userState) {
            if ((this.UrunDogrulamaBildirOperationCompleted == null)) {
                this.UrunDogrulamaBildirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUrunDogrulamaBildirOperationCompleted);
            }
            this.InvokeAsync("UrunDogrulamaBildir", new object[] {
                        UrunDogrulamaBildirim}, this.UrunDogrulamaBildirOperationCompleted, userState);
        }
        
        private void OnUrunDogrulamaBildirOperationCompleted(object arg) {
            if ((this.UrunDogrulamaBildirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UrunDogrulamaBildirCompleted(this, new UrunDogrulamaBildirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/UrunDogrulama/Genel")]
    public partial class UrunDogrulamaBildirimType {
        
        private string dtField;
        
        private string frField;
        
        private UrunDogrulamaBildirimTypeURUN[] uRUNLERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DT {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FR {
            get {
                return this.frField;
            }
            set {
                this.frField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("URUN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UrunDogrulamaBildirimTypeURUN[] URUNLER {
            get {
                return this.uRUNLERField;
            }
            set {
                this.uRUNLERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/UrunDogrulama/Genel")]
    public partial class UrunDogrulamaBildirimTypeURUN {
        
        private string gTINField;
        
        private string bnField;
        
        private string snField;
        
        private System.DateTime xdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GTIN {
            get {
                return this.gTINField;
            }
            set {
                this.gTINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BN {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SN {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime XD {
            get {
                return this.xdField;
            }
            set {
                this.xdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/UrunDogrulama/Genel")]
    public partial class UrunDogrulamaBildirimCevapType {
        
        private string bILDIRIMIDField;
        
        private UrunDogrulamaBildirimCevapTypeURUNDURUM[] uRUNLERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILDIRIMID {
            get {
                return this.bILDIRIMIDField;
            }
            set {
                this.bILDIRIMIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("URUNDURUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UrunDogrulamaBildirimCevapTypeURUNDURUM[] URUNLER {
            get {
                return this.uRUNLERField;
            }
            set {
                this.uRUNLERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/UrunDogrulama/Genel")]
    public partial class UrunDogrulamaBildirimCevapTypeURUNDURUM {
        
        private string gTINField;
        
        private string snField;
        
        private string ucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GTIN {
            get {
                return this.gTINField;
            }
            set {
                this.gTINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SN {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UC {
            get {
                return this.ucField;
            }
            set {
                this.ucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UrunDogrulamaBildirCompletedEventHandler(object sender, UrunDogrulamaBildirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UrunDogrulamaBildirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UrunDogrulamaBildirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UrunDogrulamaBildirimCevapType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UrunDogrulamaBildirimCevapType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591