//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Kaynak kodu Microsoft.VSDesigner tarafından otomatik üretilmiş , Sürüm 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DeclarationServices.PTSSendService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: 'http://its.iegm.gov.tr/pts/sendpackage' ad alanındaki 'sendFile' işlem bağlaması yoksayıldı.  Eksik soap:body giriş bağlaması.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PackageSenderWSPortBinding", Namespace="http://its.iegm.gov.tr/pts/sendpackage")]
    public partial class PackageSenderWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sendFileStreamOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PackageSenderWebService() {
            this.Url = global::DeclarationServices.Properties.Settings.Default.DeclarationServices_PTSSendService_PackageSenderWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendFileStreamCompletedEventHandler sendFileStreamCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("sendFileResponse", Namespace="http://its.iegm.gov.tr/pts/sendpackage")]
        public sendFileResponseType sendFileStream([System.Xml.Serialization.XmlElementAttribute(Namespace="http://its.iegm.gov.tr/pts/sendpackage")] sendFileStreamParametersType sendFileStreamParameters) {
            object[] results = this.Invoke("sendFileStream", new object[] {
                        sendFileStreamParameters});
            return ((sendFileResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void sendFileStreamAsync(sendFileStreamParametersType sendFileStreamParameters) {
            this.sendFileStreamAsync(sendFileStreamParameters, null);
        }
        
        /// <remarks/>
        public void sendFileStreamAsync(sendFileStreamParametersType sendFileStreamParameters, object userState) {
            if ((this.sendFileStreamOperationCompleted == null)) {
                this.sendFileStreamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendFileStreamOperationCompleted);
            }
            this.InvokeAsync("sendFileStream", new object[] {
                        sendFileStreamParameters}, this.sendFileStreamOperationCompleted, userState);
        }
        
        private void OnsendFileStreamOperationCompleted(object arg) {
            if ((this.sendFileStreamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendFileStreamCompleted(this, new sendFileStreamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://its.iegm.gov.tr/pts/sendpackage")]
    public partial class sendFileStreamParametersType {
        
        private sendFileParametersType sendFileParametersField;
        
        private byte[] fileStreamElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sendFileParametersType sendFileParameters {
            get {
                return this.sendFileParametersField;
            }
            set {
                this.sendFileParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] fileStreamElement {
            get {
                return this.fileStreamElementField;
            }
            set {
                this.fileStreamElementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://its.iegm.gov.tr/pts/sendpackage")]
    public partial class sendFileParametersType {
        
        private string sourceGLNField;
        
        private string destinationGLNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sourceGLN {
            get {
                return this.sourceGLNField;
            }
            set {
                this.sourceGLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destinationGLN {
            get {
                return this.destinationGLNField;
            }
            set {
                this.destinationGLNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://its.iegm.gov.tr/pts/sendpackage")]
    public partial class sendFileResponseType {
        
        private long transferIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long transferId {
            get {
                return this.transferIdField;
            }
            set {
                this.transferIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void sendFileStreamCompletedEventHandler(object sender, sendFileStreamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendFileStreamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendFileStreamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sendFileResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sendFileResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591