<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
             xmlns:wsp="http://www.w3.org/ns/ws-policy" 
			 xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" 
			 xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" 
			 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
			 xmlns:tns="http://its.iegm.gov.tr/p2/cancellation/dispatch" 
			 xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
			 xmlns="http://schemas.xmlsoap.org/wsdl/" 
			 targetNamespace="http://its.iegm.gov.tr/p2/cancellation/dispatch" 
			 name="DispatchCancellation">
<types>
	<xsd:schema>
		<xsd:import namespace="http://its.iegm.gov.tr/p2/cancellation/dispatch" 
					schemaLocation="http://its.saglik.gov.tr:80/ITSServices/DispatchCancellation?xsd=1"/>
	</xsd:schema>
</types>
<message name="sendDispatchCancellation">
	<part name="body" element="tns:DispatchCancellationRequest"/>
</message>
<message name="sendDispatchCancellationResponse">
	<part name="body" element="tns:DispatchCancellationResponse"/>
</message>
<message name="ItsError">
	<part name="fault" element="tns:itsError"/>
</message>
<portType name="DispatchCancellationReceiver">
	<operation name="sendDispatchCancellation">
		<input wsam:Action="http://its.iegm.gov.tr/p2/cancellation/dispatch/ItsRequest" 
			   message="tns:sendDispatchCancellation"/>
		<output wsam:Action="http://its.iegm.gov.tr/p2/cancellation/dispatch/DispatchCancellationReceiver/sendDispatchCancellationResponse" 
				message="tns:sendDispatchCancellationResponse"/>
		<fault message="tns:ItsError" 
			   name="ItsError" 
			   wsam:Action="http://its.iegm.gov.tr/p2/cancellation/dispatch/DispatchCancellationReceiver/sendDispatchCancellation/Fault/ItsError"/>
	</operation>
</portType>
<binding name="DispatchCancellationPortBinding" type="tns:DispatchCancellationReceiver">
	<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
	<operation name="sendDispatchCancellation">
		<soap:operation soapAction="http://its.iegm.gov.tr/p2/cancellation/dispatch/ItsRequest"/>
		<input><soap:body use="literal"/></input>
		<output><soap:body use="literal"/></output>
		<fault name="ItsError"><soap:fault name="ItsError" use="literal"/></fault>
	</operation>
</binding>
<service name="DispatchCancellation">
	<port name="DispatchCancellationPort" binding="tns:DispatchCancellationPortBinding">
		<soap:address location="http://its.saglik.gov.tr:80/ITSServices/DispatchCancellation"/>
	</port>
</service>
</definitions>