//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class transfer
{

    private string sourceGLNField;

    private string destinationGLNField;

    private string actionTypeField;

    private string shipToField;

    private string documentNumberField;

    private System.DateTime documentDateField;

    private bool documentDateFieldSpecified;

    private string noteField;

    private string versionField;

    private carrierType[] carrierField;

    /// <remarks/>
    public string sourceGLN
    {
        get
        {
            return this.sourceGLNField;
        }
        set
        {
            this.sourceGLNField = value;
        }
    }

    /// <remarks/>
    public string destinationGLN
    {
        get
        {
            return this.destinationGLNField;
        }
        set
        {
            this.destinationGLNField = value;
        }
    }

    /// <remarks/>
    public string actionType
    {
        get
        {
            return this.actionTypeField;
        }
        set
        {
            this.actionTypeField = value;
        }
    }

    /// <remarks/>
    public string shipTo
    {
        get
        {
            return this.shipToField;
        }
        set
        {
            this.shipToField = value;
        }
    }

    /// <remarks/>
    public string documentNumber
    {
        get
        {
            return this.documentNumberField;
        }
        set
        {
            this.documentNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime documentDate
    {
        get
        {
            return this.documentDateField;
        }
        set
        {
            this.documentDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool documentDateSpecified
    {
        get
        {
            return this.documentDateFieldSpecified;
        }
        set
        {
            this.documentDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    public string note
    {
        get
        {
            return this.noteField;
        }
        set
        {
            this.noteField = value;
        }
    }

    /// <remarks/>
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("carrier")]
    public carrierType[] carrier
    {
        get
        {
            return this.carrierField;
        }
        set
        {
            this.carrierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class carrierType
{

    private object[] itemsField;

    private string carrierLabelField;

    private string containerTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("carrier", typeof(carrierType))]
    [System.Xml.Serialization.XmlElementAttribute("productList", typeof(productListType))]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string carrierLabel
    {
        get
        {
            return this.carrierLabelField;
        }
        set
        {
            this.carrierLabelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string containerType
    {
        get
        {
            return this.containerTypeField;
        }
        set
        {
            this.containerTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class productListType
{

    private string[] serialNumberField;

    private string gTINField;

    private string lotNumberField;

    private System.DateTime productionDateField;

    private bool productionDateFieldSpecified;

    private System.DateTime expirationDateField;

    private string pONumberField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("serialNumber")]
    public string[] serialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GTIN
    {
        get
        {
            return this.gTINField;
        }
        set
        {
            this.gTINField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lotNumber
    {
        get
        {
            return this.lotNumberField;
        }
        set
        {
            this.lotNumberField = value;
        }
    }



    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    public System.DateTime productionDate
    {
        get
        {
            return this.productionDateField;
        }
        set
        {
            this.productionDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool productionDateSpecified
    {
        get
        {
            return this.productionDateFieldSpecified;
        }
        set
        {
            this.productionDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    public System.DateTime expirationDate
    {
        get
        {
            return this.expirationDateField;
        }
        set
        {
            this.expirationDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PONumber
    {
        get
        {
            return this.pONumberField;
        }
        set
        {
            this.pONumberField = value;
        }
    }
}
