//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunDogrulama.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://its.saglik.gov.tr:80/EczaneDogrulama/EczaneDogrulamaReceiverService")]
        public string UrunDogrulama_EczaneUrunDogrulama_EczaneDogrulamaReceiverService {
            get {
                return ((string)(this["UrunDogrulama_EczaneUrunDogrulama_EczaneDogrulamaReceiverService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://its.saglik.gov.tr:80/UreticiDogrulama/UreticiDogrulamaReceiverService")]
        public string UrunDogrulama_UreticiUrunDogrulama_UreticiDogrulamaReceiverService {
            get {
                return ((string)(this["UrunDogrulama_UreticiUrunDogrulama_UreticiDogrulamaReceiverService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://its.saglik.gov.tr:80/DepoDogrulama/DepoDogrulamaReceiverService")]
        public string UrunDogrulama_DepoUrunDogrulama_DepoDogrulamaReceiverService {
            get {
                return ((string)(this["UrunDogrulama_DepoUrunDogrulama_DepoDogrulamaReceiverService"]));
            }
        }
    }
}
