//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Kaynak kodu Microsoft.VSDesigner tarafından otomatik üretilmiş , Sürüm 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DeclarationServices.DeactivationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DeaktivasyonBildirimReceiverBinding", Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Deaktivasyon")]
    public partial class DeaktivasyonBildirimReceiverService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeaktivasyonBildirOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DeaktivasyonBildirimReceiverService() {
            this.Url = global::DeclarationServices.Properties.Settings.Default.DeclarationServices_DeactivationService_DeaktivasyonBildirimReceiverService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeaktivasyonBildirCompletedEventHandler DeaktivasyonBildirCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://its.iegm.gov.tr/bildirim/BildirimReceiver/v1/DeaktivasyonBildirRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeaktivasyonBildirimCevap", Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Deaktivasyon")]
        public DeaktivasyonBildirimCevapType DeaktivasyonBildir([System.Xml.Serialization.XmlElementAttribute(Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Deaktivasyon")] DeaktivasyonBildirimType DeaktivasyonBildirim) {
            object[] results = this.Invoke("DeaktivasyonBildir", new object[] {
                        DeaktivasyonBildirim});
            return ((DeaktivasyonBildirimCevapType)(results[0]));
        }
        
        /// <remarks/>
        public void DeaktivasyonBildirAsync(DeaktivasyonBildirimType DeaktivasyonBildirim) {
            this.DeaktivasyonBildirAsync(DeaktivasyonBildirim, null);
        }
        
        /// <remarks/>
        public void DeaktivasyonBildirAsync(DeaktivasyonBildirimType DeaktivasyonBildirim, object userState) {
            if ((this.DeaktivasyonBildirOperationCompleted == null)) {
                this.DeaktivasyonBildirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeaktivasyonBildirOperationCompleted);
            }
            this.InvokeAsync("DeaktivasyonBildir", new object[] {
                        DeaktivasyonBildirim}, this.DeaktivasyonBildirOperationCompleted, userState);
        }
        
        private void OnDeaktivasyonBildirOperationCompleted(object arg) {
            if ((this.DeaktivasyonBildirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeaktivasyonBildirCompleted(this, new DeaktivasyonBildirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Deaktivasyon")]
    public partial class DeaktivasyonBildirimType {
        
        private string dtField;
        
        private string frField;
        
        private string dsField;
        
        private string iSACIKLAMAField;
        
        private DeaktivasyonBildirimTypeBELGE bELGEField;
        
        private DeaktivasyonBildirimTypeURUN[] uRUNLERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DT {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FR {
            get {
                return this.frField;
            }
            set {
                this.frField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DS {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISACIKLAMA {
            get {
                return this.iSACIKLAMAField;
            }
            set {
                this.iSACIKLAMAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public DeaktivasyonBildirimTypeBELGE BELGE {
            get {
                return this.bELGEField;
            }
            set {
                this.bELGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("URUN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DeaktivasyonBildirimTypeURUN[] URUNLER {
            get {
                return this.uRUNLERField;
            }
            set {
                this.uRUNLERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Deaktivasyon")]
    public partial class DeaktivasyonBildirimTypeBELGE {
        
        private System.DateTime ddField;
        
        private string dnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DD {
            get {
                return this.ddField;
            }
            set {
                this.ddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string DN {
            get {
                return this.dnField;
            }
            set {
                this.dnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Deaktivasyon")]
    public partial class DeaktivasyonBildirimCevapType {
        
        private string bILDIRIMIDField;
        
        private DeaktivasyonBildirimCevapTypeURUNDURUM[] uRUNLERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILDIRIMID {
            get {
                return this.bILDIRIMIDField;
            }
            set {
                this.bILDIRIMIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("URUNDURUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DeaktivasyonBildirimCevapTypeURUNDURUM[] URUNLER {
            get {
                return this.uRUNLERField;
            }
            set {
                this.uRUNLERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Deaktivasyon")]
    public partial class DeaktivasyonBildirimCevapTypeURUNDURUM {
        
        private string gTINField;
        
        private string snField;
        
        private string ucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GTIN {
            get {
                return this.gTINField;
            }
            set {
                this.gTINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SN {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UC {
            get {
                return this.ucField;
            }
            set {
                this.ucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://its.iegm.gov.tr/bildirim/BR/v1/Deaktivasyon")]
    public partial class DeaktivasyonBildirimTypeURUN {
        
        private string gTINField;
        
        private string bnField;
        
        private string snField;
        
        private System.DateTime xdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GTIN {
            get {
                return this.gTINField;
            }
            set {
                this.gTINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BN {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SN {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime XD {
            get {
                return this.xdField;
            }
            set {
                this.xdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeaktivasyonBildirCompletedEventHandler(object sender, DeaktivasyonBildirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeaktivasyonBildirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeaktivasyonBildirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeaktivasyonBildirimCevapType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeaktivasyonBildirimCevapType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591