//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Kaynak kodu Microsoft.VSDesigner tarafından otomatik üretilmiş , Sürüm 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DeclarationServices.PTSTransferHelperService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PackageTransferHelperWSPortBinding", Namespace="http://its.iegm.gov.tr/pts/helper/receiveTrasnferDetails")]
    public partial class PackageTransferHelperWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback receiveTransferDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PackageTransferHelperWebService() {
            this.Url = global::DeclarationServices.Properties.Settings.Default.DeclarationServices_PTSTransferHelperService_PackageTransferHelperWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event receiveTransferDetailsCompletedEventHandler receiveTransferDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("receiveTransferDetailsResponse", Namespace="http://its.iegm.gov.tr/pts/helper/receiveTrasnferDetails")]
        public receiveTransferDetailsResponseType receiveTransferDetails([System.Xml.Serialization.XmlElementAttribute(Namespace="http://its.iegm.gov.tr/pts/helper/receiveTrasnferDetails")] receiveTransferDetailsParametersType receiveTransferDetailsParameters) {
            object[] results = this.Invoke("receiveTransferDetails", new object[] {
                        receiveTransferDetailsParameters});
            return ((receiveTransferDetailsResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void receiveTransferDetailsAsync(receiveTransferDetailsParametersType receiveTransferDetailsParameters) {
            this.receiveTransferDetailsAsync(receiveTransferDetailsParameters, null);
        }
        
        /// <remarks/>
        public void receiveTransferDetailsAsync(receiveTransferDetailsParametersType receiveTransferDetailsParameters, object userState) {
            if ((this.receiveTransferDetailsOperationCompleted == null)) {
                this.receiveTransferDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceiveTransferDetailsOperationCompleted);
            }
            this.InvokeAsync("receiveTransferDetails", new object[] {
                        receiveTransferDetailsParameters}, this.receiveTransferDetailsOperationCompleted, userState);
        }
        
        private void OnreceiveTransferDetailsOperationCompleted(object arg) {
            if ((this.receiveTransferDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receiveTransferDetailsCompleted(this, new receiveTransferDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://its.iegm.gov.tr/pts/helper/receiveTrasnferDetails")]
    public partial class receiveTransferDetailsParametersType {
        
        private string sourceGLNField;
        
        private string destinationGLNField;
        
        private bool bringNotReceivedTransferInfoField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        public receiveTransferDetailsParametersType() {
            this.bringNotReceivedTransferInfoField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sourceGLN {
            get {
                return this.sourceGLNField;
            }
            set {
                this.sourceGLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destinationGLN {
            get {
                return this.destinationGLNField;
            }
            set {
                this.destinationGLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bringNotReceivedTransferInfo {
            get {
                return this.bringNotReceivedTransferInfoField;
            }
            set {
                this.bringNotReceivedTransferInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://its.iegm.gov.tr/pts/helper/receiveTrasnferDetails")]
    public partial class receiveTransferDetailsResponseType {
        
        private receiveTransferDetailsResponseTypeTransferDetails transferDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public receiveTransferDetailsResponseTypeTransferDetails transferDetails {
            get {
                return this.transferDetailsField;
            }
            set {
                this.transferDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://its.iegm.gov.tr/pts/helper/receiveTrasnferDetails")]
    public partial class receiveTransferDetailsResponseTypeTransferDetails {
        
        private receiveTransferDetailsResponseTypeTransferDetailsTransferDetail[] transferDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transferDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public receiveTransferDetailsResponseTypeTransferDetailsTransferDetail[] transferDetail {
            get {
                return this.transferDetailField;
            }
            set {
                this.transferDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://its.iegm.gov.tr/pts/helper/receiveTrasnferDetails")]
    public partial class receiveTransferDetailsResponseTypeTransferDetailsTransferDetail {
        
        private string sourceGLNField;
        
        private string destinationGLNField;
        
        private long transferIdField;
        
        private System.DateTime transferDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sourceGLN {
            get {
                return this.sourceGLNField;
            }
            set {
                this.sourceGLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destinationGLN {
            get {
                return this.destinationGLNField;
            }
            set {
                this.destinationGLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long transferId {
            get {
                return this.transferIdField;
            }
            set {
                this.transferIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime transferDate {
            get {
                return this.transferDateField;
            }
            set {
                this.transferDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void receiveTransferDetailsCompletedEventHandler(object sender, receiveTransferDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receiveTransferDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal receiveTransferDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public receiveTransferDetailsResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((receiveTransferDetailsResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591