//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeclarationServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://212.174.130.240:8080/UretimBildirim/UretimBildirimReceiverService")]
        public string DeclarationServices_ProductionService_UretimBildirimReceiverService {
            get {
                return ((string)(this["DeclarationServices_ProductionService_UretimBildirimReceiverService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ITSDEV;Initial Catalog=ITS;Persist Security Info=True;User ID=ITS_USE" +
            "R;Password=fast")]
        public string ITSConnectionString {
            get {
                return ((string)(this["ITSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://212.174.130.240:8080/DeaktivasyonBildirim/DeaktivasyonBildirimReceiverServ" +
            "ice")]
        public string DeclarationServices_DeactivationService_DeaktivasyonBildirimReceiverService {
            get {
                return ((string)(this["DeclarationServices_DeactivationService_DeaktivasyonBildirimReceiverService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pts.saglik.gov.tr:80/PTS/PackageSenderWebService")]
        public string DeclarationServices_PTSSendService_PackageSenderWebService {
            get {
                return ((string)(this["DeclarationServices_PTSSendService_PackageSenderWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://its.saglik.gov.tr:80/ITSServices/DispatchNotification")]
        public string DeclarationServices_SalesService_UreticiSatisReceiverService {
            get {
                return ((string)(this["DeclarationServices_SalesService_UreticiSatisReceiverService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://its.saglik.gov.tr:80/UrunDogrulama/UrunDogrulamaReceiverService")]
        public string DeclarationServices_VerificationService_UrunDogrulamaReceiverService {
            get {
                return ((string)(this["DeclarationServices_VerificationService_UrunDogrulamaReceiverService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://its.saglik.gov.tr:80/ITSServices/DispatchCancellation")]
        public string DeclarationServices_SalesCancelService_UreticiSatisIptalReceiverService {
            get {
                return ((string)(this["DeclarationServices_SalesCancelService_UreticiSatisIptalReceiverService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://its.saglik.gov.tr:80/ReferenceServices/ErrorCode")]
        public string DeclarationServices_ErrorCodes_ErrorCode {
            get {
                return ((string)(this["DeclarationServices_ErrorCodes_ErrorCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://its.saglik.gov.tr:80/ITSServices/ReceiptNotification")]
        public string DeclarationServices_ReceiptService_ReceiptNotification {
            get {
                return ((string)(this["DeclarationServices_ReceiptService_ReceiptNotification"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pts.saglik.gov.tr:80/PTSHelper/PackageTransferHelperWebService")]
        public string DeclarationServices_PTSTransferHelperService_PackageTransferHelperWebService {
            get {
                return ((string)(this["DeclarationServices_PTSTransferHelperService_PackageTransferHelperWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pts.saglik.gov.tr:80/PTS/PackageReceiverWebService")]
        public string DeclarationServices_PTSReceiverService_PackageReceiverWebService {
            get {
                return ((string)(this["DeclarationServices_PTSReceiverService_PackageReceiverWebService"]));
            }
        }
    }
}
