#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TTS_Plant_230")]
	public partial class TTSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB034_WH_OUT_ORDER(TB034_WH_OUT_ORDER instance);
    partial void UpdateTB034_WH_OUT_ORDER(TB034_WH_OUT_ORDER instance);
    partial void DeleteTB034_WH_OUT_ORDER(TB034_WH_OUT_ORDER instance);
    partial void InsertTB135_WH_OUTORDERS_BOM(TB135_WH_OUTORDERS_BOM instance);
    partial void UpdateTB135_WH_OUTORDERS_BOM(TB135_WH_OUTORDERS_BOM instance);
    partial void DeleteTB135_WH_OUTORDERS_BOM(TB135_WH_OUTORDERS_BOM instance);
    #endregion
		
		public TTSDataContext() : 
				base(global::LINQ.Properties.Settings.Default.TTS_Plant_230ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TTSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TTSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TTSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TTSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB034_WH_OUT_ORDER> TB034_WH_OUT_ORDERs
		{
			get
			{
				return this.GetTable<TB034_WH_OUT_ORDER>();
			}
		}
		
		public System.Data.Linq.Table<TB135_WH_OUTORDERS_BOM> TB135_WH_OUTORDERS_BOMs
		{
			get
			{
				return this.GetTable<TB135_WH_OUTORDERS_BOM>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wms_MoveOrderToOldWarehouseDB")]
		public ISingleResult<sp_wms_MoveOrderToOldWarehouseDBResult> sp_wms_MoveOrderToOldWarehouseDB([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderId", DbType="VarChar(20)")] string orderId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderId);
			return ((ISingleResult<sp_wms_MoveOrderToOldWarehouseDBResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB034_WH_OUT_ORDERS")]
	public partial class TB034_WH_OUT_ORDER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TB034_OUT_ORDER_ID;
		
		private char _TB034_TYPE;
		
		private System.DateTime _TB034_DELIVERY_TS;
		
		private string _TB034_KIND;
		
		private System.Nullable<int> _TB034_CUSTOMER_ID;
		
		private string _TB034_CARRIER;
		
		private string _TB034_CARRIER_TRUCK;
		
		private string _TB034_FREE_TEXT1;
		
		private string _TB034_FREE_TEXT2;
		
		private string _TB034_FREE_TEXT3;
		
		private char _TB034_STATUS;
		
		private System.DateTime _TB034_SCHED_TIMESTAMP;
		
		private System.Nullable<System.DateTime> _TB034_OPEN_TIMESTAMP;
		
		private System.Nullable<System.DateTime> _TB034_MANAGED_TS;
		
		private System.Nullable<System.DateTime> _TB034_PAUSE_TIMESTAMP;
		
		private System.Nullable<System.DateTime> _TB034_COMPLETED_TS;
		
		private System.Nullable<System.DateTime> _TB034_CLOSED_TIMESTAMP;
		
		private System.Nullable<System.DateTime> _TB034_RETURN_TIMESTAMP;
		
		private char _TB034_SSCC_EXT_DIGIT;
		
		private string _TB034_SSCC_GLN_PREFIX;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTB034_OUT_ORDER_IDChanging(string value);
    partial void OnTB034_OUT_ORDER_IDChanged();
    partial void OnTB034_TYPEChanging(char value);
    partial void OnTB034_TYPEChanged();
    partial void OnTB034_DELIVERY_TSChanging(System.DateTime value);
    partial void OnTB034_DELIVERY_TSChanged();
    partial void OnTB034_KINDChanging(string value);
    partial void OnTB034_KINDChanged();
    partial void OnTB034_CUSTOMER_IDChanging(System.Nullable<int> value);
    partial void OnTB034_CUSTOMER_IDChanged();
    partial void OnTB034_CARRIERChanging(string value);
    partial void OnTB034_CARRIERChanged();
    partial void OnTB034_CARRIER_TRUCKChanging(string value);
    partial void OnTB034_CARRIER_TRUCKChanged();
    partial void OnTB034_FREE_TEXT1Changing(string value);
    partial void OnTB034_FREE_TEXT1Changed();
    partial void OnTB034_FREE_TEXT2Changing(string value);
    partial void OnTB034_FREE_TEXT2Changed();
    partial void OnTB034_FREE_TEXT3Changing(string value);
    partial void OnTB034_FREE_TEXT3Changed();
    partial void OnTB034_STATUSChanging(char value);
    partial void OnTB034_STATUSChanged();
    partial void OnTB034_SCHED_TIMESTAMPChanging(System.DateTime value);
    partial void OnTB034_SCHED_TIMESTAMPChanged();
    partial void OnTB034_OPEN_TIMESTAMPChanging(System.Nullable<System.DateTime> value);
    partial void OnTB034_OPEN_TIMESTAMPChanged();
    partial void OnTB034_MANAGED_TSChanging(System.Nullable<System.DateTime> value);
    partial void OnTB034_MANAGED_TSChanged();
    partial void OnTB034_PAUSE_TIMESTAMPChanging(System.Nullable<System.DateTime> value);
    partial void OnTB034_PAUSE_TIMESTAMPChanged();
    partial void OnTB034_COMPLETED_TSChanging(System.Nullable<System.DateTime> value);
    partial void OnTB034_COMPLETED_TSChanged();
    partial void OnTB034_CLOSED_TIMESTAMPChanging(System.Nullable<System.DateTime> value);
    partial void OnTB034_CLOSED_TIMESTAMPChanged();
    partial void OnTB034_RETURN_TIMESTAMPChanging(System.Nullable<System.DateTime> value);
    partial void OnTB034_RETURN_TIMESTAMPChanged();
    partial void OnTB034_SSCC_EXT_DIGITChanging(char value);
    partial void OnTB034_SSCC_EXT_DIGITChanged();
    partial void OnTB034_SSCC_GLN_PREFIXChanging(string value);
    partial void OnTB034_SSCC_GLN_PREFIXChanged();
    #endregion
		
		public TB034_WH_OUT_ORDER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_OUT_ORDER_ID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TB034_OUT_ORDER_ID
		{
			get
			{
				return this._TB034_OUT_ORDER_ID;
			}
			set
			{
				if ((this._TB034_OUT_ORDER_ID != value))
				{
					this.OnTB034_OUT_ORDER_IDChanging(value);
					this.SendPropertyChanging();
					this._TB034_OUT_ORDER_ID = value;
					this.SendPropertyChanged("TB034_OUT_ORDER_ID");
					this.OnTB034_OUT_ORDER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_TYPE", DbType="Char(1) NOT NULL")]
		public char TB034_TYPE
		{
			get
			{
				return this._TB034_TYPE;
			}
			set
			{
				if ((this._TB034_TYPE != value))
				{
					this.OnTB034_TYPEChanging(value);
					this.SendPropertyChanging();
					this._TB034_TYPE = value;
					this.SendPropertyChanged("TB034_TYPE");
					this.OnTB034_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_DELIVERY_TS", DbType="DateTime NOT NULL")]
		public System.DateTime TB034_DELIVERY_TS
		{
			get
			{
				return this._TB034_DELIVERY_TS;
			}
			set
			{
				if ((this._TB034_DELIVERY_TS != value))
				{
					this.OnTB034_DELIVERY_TSChanging(value);
					this.SendPropertyChanging();
					this._TB034_DELIVERY_TS = value;
					this.SendPropertyChanged("TB034_DELIVERY_TS");
					this.OnTB034_DELIVERY_TSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_KIND", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TB034_KIND
		{
			get
			{
				return this._TB034_KIND;
			}
			set
			{
				if ((this._TB034_KIND != value))
				{
					this.OnTB034_KINDChanging(value);
					this.SendPropertyChanging();
					this._TB034_KIND = value;
					this.SendPropertyChanged("TB034_KIND");
					this.OnTB034_KINDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_CUSTOMER_ID", DbType="Int")]
		public System.Nullable<int> TB034_CUSTOMER_ID
		{
			get
			{
				return this._TB034_CUSTOMER_ID;
			}
			set
			{
				if ((this._TB034_CUSTOMER_ID != value))
				{
					this.OnTB034_CUSTOMER_IDChanging(value);
					this.SendPropertyChanging();
					this._TB034_CUSTOMER_ID = value;
					this.SendPropertyChanged("TB034_CUSTOMER_ID");
					this.OnTB034_CUSTOMER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_CARRIER", DbType="VarChar(30)")]
		public string TB034_CARRIER
		{
			get
			{
				return this._TB034_CARRIER;
			}
			set
			{
				if ((this._TB034_CARRIER != value))
				{
					this.OnTB034_CARRIERChanging(value);
					this.SendPropertyChanging();
					this._TB034_CARRIER = value;
					this.SendPropertyChanged("TB034_CARRIER");
					this.OnTB034_CARRIERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_CARRIER_TRUCK", DbType="VarChar(20)")]
		public string TB034_CARRIER_TRUCK
		{
			get
			{
				return this._TB034_CARRIER_TRUCK;
			}
			set
			{
				if ((this._TB034_CARRIER_TRUCK != value))
				{
					this.OnTB034_CARRIER_TRUCKChanging(value);
					this.SendPropertyChanging();
					this._TB034_CARRIER_TRUCK = value;
					this.SendPropertyChanged("TB034_CARRIER_TRUCK");
					this.OnTB034_CARRIER_TRUCKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_FREE_TEXT1", DbType="VarChar(80)")]
		public string TB034_FREE_TEXT1
		{
			get
			{
				return this._TB034_FREE_TEXT1;
			}
			set
			{
				if ((this._TB034_FREE_TEXT1 != value))
				{
					this.OnTB034_FREE_TEXT1Changing(value);
					this.SendPropertyChanging();
					this._TB034_FREE_TEXT1 = value;
					this.SendPropertyChanged("TB034_FREE_TEXT1");
					this.OnTB034_FREE_TEXT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_FREE_TEXT2", DbType="VarChar(80)")]
		public string TB034_FREE_TEXT2
		{
			get
			{
				return this._TB034_FREE_TEXT2;
			}
			set
			{
				if ((this._TB034_FREE_TEXT2 != value))
				{
					this.OnTB034_FREE_TEXT2Changing(value);
					this.SendPropertyChanging();
					this._TB034_FREE_TEXT2 = value;
					this.SendPropertyChanged("TB034_FREE_TEXT2");
					this.OnTB034_FREE_TEXT2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_FREE_TEXT3", DbType="VarChar(80)")]
		public string TB034_FREE_TEXT3
		{
			get
			{
				return this._TB034_FREE_TEXT3;
			}
			set
			{
				if ((this._TB034_FREE_TEXT3 != value))
				{
					this.OnTB034_FREE_TEXT3Changing(value);
					this.SendPropertyChanging();
					this._TB034_FREE_TEXT3 = value;
					this.SendPropertyChanged("TB034_FREE_TEXT3");
					this.OnTB034_FREE_TEXT3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_STATUS", DbType="Char(1) NOT NULL")]
		public char TB034_STATUS
		{
			get
			{
				return this._TB034_STATUS;
			}
			set
			{
				if ((this._TB034_STATUS != value))
				{
					this.OnTB034_STATUSChanging(value);
					this.SendPropertyChanging();
					this._TB034_STATUS = value;
					this.SendPropertyChanged("TB034_STATUS");
					this.OnTB034_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_SCHED_TIMESTAMP", DbType="DateTime NOT NULL")]
		public System.DateTime TB034_SCHED_TIMESTAMP
		{
			get
			{
				return this._TB034_SCHED_TIMESTAMP;
			}
			set
			{
				if ((this._TB034_SCHED_TIMESTAMP != value))
				{
					this.OnTB034_SCHED_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._TB034_SCHED_TIMESTAMP = value;
					this.SendPropertyChanged("TB034_SCHED_TIMESTAMP");
					this.OnTB034_SCHED_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_OPEN_TIMESTAMP", DbType="DateTime")]
		public System.Nullable<System.DateTime> TB034_OPEN_TIMESTAMP
		{
			get
			{
				return this._TB034_OPEN_TIMESTAMP;
			}
			set
			{
				if ((this._TB034_OPEN_TIMESTAMP != value))
				{
					this.OnTB034_OPEN_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._TB034_OPEN_TIMESTAMP = value;
					this.SendPropertyChanged("TB034_OPEN_TIMESTAMP");
					this.OnTB034_OPEN_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_MANAGED_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TB034_MANAGED_TS
		{
			get
			{
				return this._TB034_MANAGED_TS;
			}
			set
			{
				if ((this._TB034_MANAGED_TS != value))
				{
					this.OnTB034_MANAGED_TSChanging(value);
					this.SendPropertyChanging();
					this._TB034_MANAGED_TS = value;
					this.SendPropertyChanged("TB034_MANAGED_TS");
					this.OnTB034_MANAGED_TSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_PAUSE_TIMESTAMP", DbType="DateTime")]
		public System.Nullable<System.DateTime> TB034_PAUSE_TIMESTAMP
		{
			get
			{
				return this._TB034_PAUSE_TIMESTAMP;
			}
			set
			{
				if ((this._TB034_PAUSE_TIMESTAMP != value))
				{
					this.OnTB034_PAUSE_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._TB034_PAUSE_TIMESTAMP = value;
					this.SendPropertyChanged("TB034_PAUSE_TIMESTAMP");
					this.OnTB034_PAUSE_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_COMPLETED_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TB034_COMPLETED_TS
		{
			get
			{
				return this._TB034_COMPLETED_TS;
			}
			set
			{
				if ((this._TB034_COMPLETED_TS != value))
				{
					this.OnTB034_COMPLETED_TSChanging(value);
					this.SendPropertyChanging();
					this._TB034_COMPLETED_TS = value;
					this.SendPropertyChanged("TB034_COMPLETED_TS");
					this.OnTB034_COMPLETED_TSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_CLOSED_TIMESTAMP", DbType="DateTime")]
		public System.Nullable<System.DateTime> TB034_CLOSED_TIMESTAMP
		{
			get
			{
				return this._TB034_CLOSED_TIMESTAMP;
			}
			set
			{
				if ((this._TB034_CLOSED_TIMESTAMP != value))
				{
					this.OnTB034_CLOSED_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._TB034_CLOSED_TIMESTAMP = value;
					this.SendPropertyChanged("TB034_CLOSED_TIMESTAMP");
					this.OnTB034_CLOSED_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_RETURN_TIMESTAMP", DbType="DateTime")]
		public System.Nullable<System.DateTime> TB034_RETURN_TIMESTAMP
		{
			get
			{
				return this._TB034_RETURN_TIMESTAMP;
			}
			set
			{
				if ((this._TB034_RETURN_TIMESTAMP != value))
				{
					this.OnTB034_RETURN_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._TB034_RETURN_TIMESTAMP = value;
					this.SendPropertyChanged("TB034_RETURN_TIMESTAMP");
					this.OnTB034_RETURN_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_SSCC_EXT_DIGIT", DbType="Char(1) NOT NULL")]
		public char TB034_SSCC_EXT_DIGIT
		{
			get
			{
				return this._TB034_SSCC_EXT_DIGIT;
			}
			set
			{
				if ((this._TB034_SSCC_EXT_DIGIT != value))
				{
					this.OnTB034_SSCC_EXT_DIGITChanging(value);
					this.SendPropertyChanging();
					this._TB034_SSCC_EXT_DIGIT = value;
					this.SendPropertyChanged("TB034_SSCC_EXT_DIGIT");
					this.OnTB034_SSCC_EXT_DIGITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB034_SSCC_GLN_PREFIX", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string TB034_SSCC_GLN_PREFIX
		{
			get
			{
				return this._TB034_SSCC_GLN_PREFIX;
			}
			set
			{
				if ((this._TB034_SSCC_GLN_PREFIX != value))
				{
					this.OnTB034_SSCC_GLN_PREFIXChanging(value);
					this.SendPropertyChanging();
					this._TB034_SSCC_GLN_PREFIX = value;
					this.SendPropertyChanged("TB034_SSCC_GLN_PREFIX");
					this.OnTB034_SSCC_GLN_PREFIXChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB135_WH_OUTORDERS_BOM")]
	public partial class TB135_WH_OUTORDERS_BOM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TB135_OUT_ORDER_ID;
		
		private string _TB135_GTIN;
		
		private int _TB135_TARGET_QTY;
		
		private int _TB135_QUANTITY;
		
		private int _TB135_COMPLETE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTB135_OUT_ORDER_IDChanging(string value);
    partial void OnTB135_OUT_ORDER_IDChanged();
    partial void OnTB135_GTINChanging(string value);
    partial void OnTB135_GTINChanged();
    partial void OnTB135_TARGET_QTYChanging(int value);
    partial void OnTB135_TARGET_QTYChanged();
    partial void OnTB135_QUANTITYChanging(int value);
    partial void OnTB135_QUANTITYChanged();
    partial void OnTB135_COMPLETEChanging(int value);
    partial void OnTB135_COMPLETEChanged();
    #endregion
		
		public TB135_WH_OUTORDERS_BOM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB135_OUT_ORDER_ID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TB135_OUT_ORDER_ID
		{
			get
			{
				return this._TB135_OUT_ORDER_ID;
			}
			set
			{
				if ((this._TB135_OUT_ORDER_ID != value))
				{
					this.OnTB135_OUT_ORDER_IDChanging(value);
					this.SendPropertyChanging();
					this._TB135_OUT_ORDER_ID = value;
					this.SendPropertyChanged("TB135_OUT_ORDER_ID");
					this.OnTB135_OUT_ORDER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB135_GTIN", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TB135_GTIN
		{
			get
			{
				return this._TB135_GTIN;
			}
			set
			{
				if ((this._TB135_GTIN != value))
				{
					this.OnTB135_GTINChanging(value);
					this.SendPropertyChanging();
					this._TB135_GTIN = value;
					this.SendPropertyChanged("TB135_GTIN");
					this.OnTB135_GTINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB135_TARGET_QTY", DbType="Int NOT NULL")]
		public int TB135_TARGET_QTY
		{
			get
			{
				return this._TB135_TARGET_QTY;
			}
			set
			{
				if ((this._TB135_TARGET_QTY != value))
				{
					this.OnTB135_TARGET_QTYChanging(value);
					this.SendPropertyChanging();
					this._TB135_TARGET_QTY = value;
					this.SendPropertyChanged("TB135_TARGET_QTY");
					this.OnTB135_TARGET_QTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB135_QUANTITY", DbType="Int NOT NULL")]
		public int TB135_QUANTITY
		{
			get
			{
				return this._TB135_QUANTITY;
			}
			set
			{
				if ((this._TB135_QUANTITY != value))
				{
					this.OnTB135_QUANTITYChanging(value);
					this.SendPropertyChanging();
					this._TB135_QUANTITY = value;
					this.SendPropertyChanged("TB135_QUANTITY");
					this.OnTB135_QUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB135_COMPLETE", DbType="Int NOT NULL")]
		public int TB135_COMPLETE
		{
			get
			{
				return this._TB135_COMPLETE;
			}
			set
			{
				if ((this._TB135_COMPLETE != value))
				{
					this.OnTB135_COMPLETEChanging(value);
					this.SendPropertyChanging();
					this._TB135_COMPLETE = value;
					this.SendPropertyChanged("TB135_COMPLETE");
					this.OnTB135_COMPLETEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_wms_MoveOrderToOldWarehouseDBResult
	{
		
		private string _Column1;
		
		public sp_wms_MoveOrderToOldWarehouseDBResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Column1", DbType="VarChar(40)")]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
