//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://its.saglik.gov.tr:80/EczaneDogrulama/EczaneDogrulamaReceiverService")]
        public string ITS_UrunDogrulama_EczaneDogrulamaReceiverService {
            get {
                return ((string)(this["ITS_UrunDogrulama_EczaneDogrulamaReceiverService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://its.saglik.gov.tr:80/UreticiDogrulama/UreticiDogrulamaReceiverService")]
        public string ITS_UreticiUrunDogrulama_UreticiDogrulamaReceiverService {
            get {
                return ((string)(this["ITS_UreticiUrunDogrulama_UreticiDogrulamaReceiverService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://its.saglik.gov.tr:80/DepoDogrulama/DepoDogrulamaReceiverService")]
        public string ITS_DepoUrunDogrulama_DepoDogrulamaReceiverService {
            get {
                return ((string)(this["ITS_DepoUrunDogrulama_DepoDogrulamaReceiverService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.117.200/TTBOWS2/TTSPlantWebService.asmx")]
        public string ITS_TTS_Main {
            get {
                return ((string)(this["ITS_TTS_Main"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pts.saglik.gov.tr/PTS/PackageReceiverWebService")]
        public string ITS_PTSAlma_PackageReceiverWebService {
            get {
                return ((string)(this["ITS_PTSAlma_PackageReceiverWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ITS;Initial Catalog=ITS;Persist Security Info=True;User ID=ITS_USER;P" +
            "assword=fast;Application Name=ITS;Workstation ID=WORKSTATION_ID")]
        public string ITSConnectionString {
            get {
                return ((string)(this["ITSConnectionString"]));
            }
        }
    }
}
